FROM alpine:latest
########################################################
# Essential packages for remote debugging and login in
########################################################
RUN apk add --no-cache zlib fuse tini bash
RUN apk add clang clang-dev libc-dev linux-headers build-base gdb libtool cmake udev eudev-dev make gcc g++ boost-dev boost-static fuse-dev zlib-dev

